# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.define "nginx" do |nginx|
    nginx.vm.box = "chavo1/xenial64base"
    nginx.vm.network "private_network", ip: "192.168.56.56"
    nginx.vm.provision "shell", path: "scripts/nginx.sh"
    
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2

    end
  end

  config.vm.define "elastic" do |elastic|
    elastic.vm.box = "chavo1/xenial64base"
    elastic.vm.network "private_network", ip: "192.168.56.57"
    elastic.vm.provision "shell", path: "scripts/elk.sh"

  config.vm.provider "virtualbox" do |v|

    v.memory = 2048
    v.cpus = 2

    end
  end
end
