# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure(2) do |config|

  config.vm.define "nginx" do |elastic|
    elastic.vm.box = "chavo1/centos7"
    elastic.vm.box_version = "0.0.1"
    elastic.vm.network "private_network", ip: "192.168.56.56"
    elastic.vm.provision "shell", path: "scripts/yum-elk.sh"
    
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2

    end
  end
end
